### ISSUE TITLE
Better differentiate timeout in ut_event_wait_or_timeout?

### ISSUE THREAD

**Issue by mmaccamy** [leok7v/xrt#1]
[ut_event_wait_or_timeout(...)](https://github.com/leok7v/ui/blob/faf4352f46bd5b158b2f7aebb332b3a1aef12765/src/ut/ut_threads.c#L28) encapsulates [WaitForSingleObject(...)](https://learn.microsoft.com/en-us/windows/win32/api/synchapi/nf-synchapi-waitforsingleobject).

At the moment, WAIT_TIMEOUT isn't distinguishable from WAIT_ABANDONED. Both result in -1 being returned.

Similar issue exists in [ut_event_wait_any_or_timeout(...)](https://github.com/leok7v/ui/blob/faf4352f46bd5b158b2f7aebb332b3a1aef12765/src/ut/ut_threads.c#L39) with its encapsulation of [WaitForMultipleObjects (...)](https://learn.microsoft.com/en-us/windows/win32/api/synchapi/nf-synchapi-waitformultipleobjects).

**Comment by leok7v** [comment]
I will, though we do not use WaitFor*Object[s]() on CRITIAL_SECTIONS or mutexes, thus for HEVENT I believe it never happens.
See:
   https://chatgpt.com/share/3d9ff833-2d1e-4bec-b308-8018784ab1eb
   
"The `WaitForSingleObject` function in the Windows API is used to wait for the state of a specified object to be signaled. The `WAIT_ABANDONED` return value is specific to mutex objects.

`WAIT_ABANDONED` is returned when the thread that owns a mutex terminates without releasing the mutex. In other words, if a thread holding a mutex exits without calling `ReleaseMutex`, any other thread that calls `WaitForSingleObject` on that mutex will receive the `WAIT_ABANDONED` status. This indicates that the mutex is released but was not properly signaled because its ownership was not orderly relinquished. This scenario is generally a sign of a programming error, as it can lead to inconsistent or unsafe states within the program due to the abrupt termination of the mutex owner.

It's important to handle this return value to ensure that the application deals correctly with the unexpected state of shared resources."


Maybe we should fail fast (fatal) on WAIT_ABANDONED since this is definitely a big ugly bug in caller logic one way or another.

**Comment by mmaccamy** [comment]
Agreed on the fail fast handling of WAIT_ABANDONED. Looks like your fail fast checks were removed on migration from old crt.h:

```
    DWORD ix = WaitForSingleObject(e, ms);
    fatal_if(ix == WAIT_FAILED);
    fatal_if(ix == WAIT_ABANDONED);
```

You'll need to resolve the behavior with [wait2e(ix)](https://github.com/leok7v/ui/blob/d7e5d32474cdadbe8a9902b129bf41407a5d5d88/single_file_lib/ut/ut.h#L1265)

**Comment by leok7v** [comment]
Agreed errors should be fatal. Verified in both situations:

```
WaitForSingleObject(null, timeout) returns WAIT_FAILED

WaitForSingleObject(e, timeout) returns WAIT_FAILED
when

static void bad_wait(void* p) {
    ut_event_t e = (ut_event_t)p;
    int32_t r = ut_event.wait_or_timeout(e, 1.0);
    traceln("r: %d", r);
}

ut_event_t e1 = ut_event.create();
ut_thread_t t1 = ut_thread.start(bad_wait, e1);
ut_thread.sleep_for(0.5);
ut_event.dispose(e1);
```

WaitForSingleObject(null, timeout) returns WAIT_FAILED not WAIT_ABANDONED
and it should be fatal.

Thus WAIT_ABANDONED is never returned for event, but 
```
#define wait2e(ix) (errno_t)                                                     \
    ((int32_t)WAIT_OBJECT_0 <= (int32_t)(ix) && (ix) <= WAIT_OBJECT_0 + 63 ? 0 : \
      ((ix) == WAIT_ABANDONED ? ERROR_REQUEST_ABORTED :                          \
        ((ix) == WAIT_TIMEOUT ? ERROR_TIMEOUT :                                  \
          ((ix) == WAIT_FAILED) ? (errno_t)GetLastError() : ERROR_INVALID_HANDLE \
        )                                                                        \
      )                                                                          \
    )
```
is used in both ut_threads.c and ut_processes.c
In ut_threads.c it indicates an error in the caller code, but in ut_processes.c
it actually legit because the wait could be on the process source code if which is out of our control and it could crash.

I will fix only in ut_threads.c leaving ut_processes.c as it is
